package com.example.compose.test.di

import com.example.compose.test.domain.ComplexEngine
import com.example.compose.test.domain.EngineBase
import com.example.compose.test.domain.SomeEngine
import dagger.Binds
import dagger.Component
import dagger.Module
import dagger.Provides
import javax.inject.Singleton

// This class is responsible for defining where to look for specific objects
@Module
interface AppModule {

    companion object {

        // Defines how to create an object
        @Singleton
        @Provides
        fun providesComplexEngine(someEngine: SomeEngine): ComplexEngine {
            return ComplexEngine(someEngine)
        }

    }

    // Provides an alias for objects. Param object maps to return object type.
    @Binds
    fun bindComplexEngine(complexEngine: ComplexEngine): EngineBase

}

// Implementation of this class is generated by Dagger.
// It creates the classes and its dependencies and returns them from these methods below.
@Component(modules = [AppModule::class])
@Singleton
interface EngineProvider {

    fun getEngine(): ComplexEngine

    fun getComplexEngine(): EngineBase
}